<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="arm">


    <xacro:include filename="include.xacro" />



    <!-- This first link called "world" is empty -->
    <link name="world"></link>


    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>        
    </joint>


    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
            <material name="green">
                <color rgba="0.2 1 0.2 1"/>
            </material>
        </visual>
        <xacro:inertial_box mass="0.05" x="0.1" y="0.1" z="0.1">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="joint1" type="revolute">
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="link_01"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>



    <xacro:property name="arm_length" value="0.04" />
    <xacro:property name="arm_radius" value="0.035" />
    <link name="link_01">
        <visual>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange1" />
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="joint2" type="revolute">
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <parent link="link_01"/>
        <child link="link_02"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <xacro:property name="arm_length" value="0.08" />
    <xacro:property name="arm_radius" value="0.015" />
    <link name="link_02">
        <visual>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange2" />
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="joint3" type="revolute">
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <parent link="link_02"/>
        <child link="link_03"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <xacro:property name="arm_length" value="0.08" />
    <xacro:property name="arm_radius" value="0.015" />
    <link name="link_03">
        <visual>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange1" />
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="joint4" type="revolute">
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <parent link="link_03"/>
        <child link="link_04"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <xacro:property name="arm_length" value="0.08" />
    <xacro:property name="arm_radius" value="0.015" />
    <link name="link_04">
        <visual>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange2" />
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="joint5" type="revolute">
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <parent link="link_04"/>
        <child link="link_05"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
    </joint>

    <xacro:property name="arm_length" value="0.025" />
    <xacro:property name="arm_radius" value="0.015" />
    <link name="link_05">
        <visual>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="blue" />
        </visual>
        <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <xacro:include filename="arm_gazebo.xacro" />


</robot>