<?xml version="1.0"?>
<robot name="mobile_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="package_name" value="robot_description" />
  <xacro:property name="robot_name" value="mobile_robot" />

  <xacro:include filename="$(find ${package_name})/urdf/include/common_macros.urdf.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/include/common_sensors.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/mobile_robot.gazebo.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/arm_include.xacro" />
  <xacro:include filename="$(find ${package_name})/urdf/arm_gazebo.xacro" />

  <xacro:property name="sensor_yaml" value="$(find ${package_name})/config/sensors.yaml" />
  <xacro:property name="sensor_prop" value="${xacro.load_yaml(sensor_yaml)}"/>

  <xacro:property name="baselen" value="0.300" />
  <xacro:property name="basewidth" value="0.190" />
  <xacro:property name="basethick" value="0.003" />
  <xacro:property name="wheeldiam" value="0.056" />
  <xacro:property name="wheelwidth" value="0.038" />
  <xacro:property name="wheel_x_pos" value="${baselen/2}" />
  <xacro:property name="wheel_y_pos" value="${wheelwidth/2+basewidth/2+.013}" />
  <xacro:property name="wheel_z_pos" value="${-((basethick/2)+(wheeldiam/2)+.007)}" />
  <!-- <xacro:property name="pi" value="3.1415926535" /> -->
  <xacro:property name="collision_inflation" value="1.1" />

  <link name="base_footprint" />
  <!-- Joint to connect base_footprint with base_link -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 ${(wheeldiam/2)+(-wheel_z_pos)}" rpy="0 0 0" />
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${baselen} ${basewidth} ${basethick}" />
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${baselen*collision_inflation} ${basewidth*collision_inflation} ${basethick*collision_inflation}" />
      </geometry>
    </collision>
    <xacro:base_inertia m="1.065" 
    x="${baselen}" y="${basewidth}" z="${basethick}" 
    o_xyz="0.0 0.0 0.0" o_rpy="0.0 0.0 0.0"
    />
  </link>

  <xacro:wheel prefix="left" suffix="front" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${wheel_x_pos-.057}" y_pos="${wheel_y_pos}" z_pos="${wheel_z_pos}" collision_inflation="${collision_inflation}"/>
  <xacro:wheel prefix="left" suffix="back" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${-wheel_x_pos+.042}" y_pos="${wheel_y_pos}" z_pos="${wheel_z_pos}" collision_inflation="${collision_inflation}"/>
  <xacro:wheel prefix="right" suffix="front" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${wheel_x_pos-.057}" y_pos="${-wheel_y_pos}" z_pos="${wheel_z_pos}" collision_inflation="${collision_inflation}"/>
  <xacro:wheel prefix="right" suffix="back" m="0.087" r="${wheeldiam/2}" l="${wheelwidth}" x_pos="${-wheel_x_pos+.042}" y_pos="${-wheel_y_pos}" z_pos="${wheel_z_pos}" collision_inflation="${collision_inflation}"/>

  <!-- <robot_arm/> -->
  <joint name="arm_robot_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link" />
    <origin xyz="0.1 0 0" rpy="0 0 0" />
  </joint>

  <link name="arm_base_link">
      <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <box size="0.1 0.1 0.005" />
          </geometry>
          <material name="green">
              <color rgba="0.2 1 0.2 1"/>
          </material>
      </visual>
      <xacro:inertial_box mass="0.05" x="0.1" y="0.1" z="0.1">
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
  </link>

  <joint name="joint1" type="revolute">
      <origin xyz="0 0 0.005" rpy="0 0 0"/>
      <parent link="arm_base_link"/>
      <child link="link_01"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
  </joint>



  <xacro:property name="arm_length" value="0.04" />
  <xacro:property name="arm_radius" value="0.035" />
  <link name="link_01">
      <visual>
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="orange1" />
      </visual>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <joint name="joint2" type="revolute">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_01"/>
      <child link="link_02"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.08" />
  <xacro:property name="arm_radius" value="0.015" />
  <link name="link_02">
      <visual>
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="orange2" />
      </visual>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <joint name="joint3" type="revolute">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_02"/>
      <child link="link_03"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.08" />
  <xacro:property name="arm_radius" value="0.015" />
  <link name="link_03">
      <visual>
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="orange1" />
      </visual>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <joint name="joint4" type="revolute">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_03"/>
      <child link="link_04"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.08" />
  <xacro:property name="arm_radius" value="0.015" />
  <link name="link_04">
      <visual>
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="orange2" />
      </visual>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <joint name="joint5" type="revolute">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_04"/>
      <child link="link_05"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-pi}" upper="${pi}" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.025" />
  <xacro:property name="arm_radius" value="0.015" />
  <link name="link_05">
      <visual>
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="yellow" />
      </visual>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>

  <joint name="finger1_joint" type="prismatic">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_05"/>
      <child link="finger_link_01"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="0.01" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.025" />
  <xacro:property name="arm_radius" value="0.005" />
  <link name="finger_link_01">
      <visual>
          <origin xyz="0 0.005 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="yellow" />
      </visual>
      <collision>
          <origin xyz="0 0.005 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="yellow" />
      </collision>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 0.15 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>  

  <joint name="finger2_joint" type="prismatic">
      <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
      <parent link="link_05"/>
      <child link="finger_link_02"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0" upper="0.01" velocity="100" effort="100"/> 
  </joint>

  <xacro:property name="arm_length" value="0.025" />
  <xacro:property name="arm_radius" value="0.005" />
  <link name="finger_link_02">
      <visual>
          <origin xyz="0 -0.005 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="yellow" />
      </visual>
      <collision>
          <origin xyz="0 -0.005 ${arm_length/2}" rpy="0 0 0"/>
          <geometry>                
              <cylinder length="${arm_length}" radius="${arm_radius}" />
          </geometry>
          <material name="yellow" />
      </collision>
      <xacro:inertial_cylinder mass="0.1" length="${arm_length}" radius="${arm_radius}">
          <origin xyz="0 -0.15 ${arm_length/2}" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
  </link>





  <!-- Sensors -->
  <xacro:gpu_laser prefix="rplidar" parent_link="base_link"
                   sensor_prop="${sensor_prop}"> 
  </xacro:gpu_laser>



</robot>